language: node_js
node_js:
  - "16"
before_install:
  - export TZ='Asia/Shanghai'
  - npm cache clean --force
install:
  - npm install
script:
  - npm run build
#  - echo "itliwei.github.io" >> .vuepress/dist/CNAME
  # 以下为编译PDF，耗时较长，可以考虑注释掉，手工触发
#  - echo "Starting to Export PDF..."
#  - sudo apt-get update
#  - sudo apt-get -y install xfonts-utils fonts-droid-fallback xfonts-intl-asian
#  - sudo cp .vuepress/font/*.* /usr/share/fonts/truetype/
#  - sudo mkfontscale && mkfontdir && fc-cache
#  - npm run export
deploy:
  - provider: pages
    cleanup: true
    skip_cleanup: true
    local_dir: .vuepress/dist
    github_token: $gh_token
    keep_history: true
    target-branch: gh-pages
    on:
      branch: master
